name: Run tests on all branches

on:
  pull_request:
  push:
    branches:
      - '*' # Run on all branches

jobs:
  test:
    name: PHP ${{ matrix.php }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      fail-fast: false
      matrix:
        php: ['8.2']
        experimental: [false]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: actions/cache@v4
        with:
          path: ~/.composer/cache/files
          key: php${{ matrix.php }}-${{ hashFiles('**/composer.lock') }}
          restore-keys: php${{ matrix.php }}-
      - run: composer install --prefer-dist --optimize-autoloader --no-interaction --no-progress
      - run: composer test
      - name: Upload test coverage
        uses: actions/upload-artifact@v4
        with:
          name: test-coverage
          path: coverage/
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          file: ./coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: Attestto-com/solana-php-sdk
